name: Auto cancel
on:
  push:
    paths:
      - ".github/workflows/auto-cancel.yml" # ワークフローファイルのみ
concurrency:
  group: $({ github.workflow }}-$({ github.ref }}
  cancel-in-progress: true #同ーグループのワークフローが実行中ならキャンセル
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
