name: Log group
on:
  push:
    paths:
      - ".github/workflows/log-group.yml" # ワークフローファイルのみ
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run:
          | # Bashのトレーシングオプションを有効化し、実行したコマンドをログ出力
          echo "::group::Show environment variables" # ロググループ化の開始
          printenv
          echo "::endgroup::" #ロググループ化の終了
