name: Multi-dimension matrix
on:
  push:
    paths:
      - ".github/workflows/multi-demension-matrix.yml" # ワークフローファイル
jobs:
  print:
    strategy:
      matrix: # 多次元マトリックスの定義
        os: [ubuntu-latest, macos-latest] # osプロパティの定義
        version: [18, 20] # versionプロパティの定義
    runs-on: ${{ matrix.os }} # osプロパティの参照
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }} # versionプロパティの参照
      - run: echo "${RUNNER_OS}" && node --version
