name: Sequential jobs
on:
  push:
    paths:
      - ".github/workflows/sequential-jobs.yml" # ワークフローファイル
jobs: # jobsキーへ複数のジョブを定義すれば、並列に実行される
  first:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "First job"
  second:
    runs-on: ubuntu-latest
    needs: [first]
    steps:
      - run: sleep 10 && echo "Second job"
  third:
    runs-on: ubuntu-latest
    needs: [second]
    steps:
      - run: sleep 10 && echo "Third job"
